# Generated by Django 3.0.1 on 2020-11-09 19:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('Sexo', models.CharField(choices=[('H', 'H'), ('D', 'D')], max_length=1, null=True)),
                ('Edad', models.IntegerField(blank=True, null=True)),
                ('Procedencia', models.CharField(max_length=100, null=True)),
                ('Trabajo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('Beca', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('Convocatoria', models.CharField(blank=True, max_length=3, null=True)),
                ('Preferencia', models.IntegerField(blank=True, null=True)),
                ('Modalidad', models.CharField(blank=True, max_length=3, null=True)),
                ('Especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('Nota_Bach_Ciclo', models.FloatField(blank=True, null=True)),
                ('Nota_Prueba', models.FloatField(blank=True, null=True)),
                ('Nota_Especifica', models.FloatField(blank=True, null=True)),
                ('Nota_Admision', models.FloatField(blank=True, null=True)),
                ('Abandono', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('creditos_matriculados_primer_año', models.IntegerField(blank=True, null=True)),
                ('creditos_presentados_primer_año', models.IntegerField(blank=True, null=True)),
                ('creditos_aprobados_primer_año', models.IntegerField(blank=True, null=True)),
                ('creditos_matriculados_segundo_año', models.IntegerField(blank=True, null=True)),
                ('creditos_presentados_segundo_año', models.IntegerField(blank=True, null=True)),
                ('creditos_aprobados_segundo_año', models.IntegerField(blank=True, null=True)),
                ('media_primer_año', models.FloatField(blank=True, null=True)),
                ('media_segundo_año', models.FloatField(blank=True, null=True)),
                ('asignaturas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('notas', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('Grado', models.CharField(max_length=150)),
                ('Ingreso', models.CharField(max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Grado_rp30',
            fields=[
                ('alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('Sexo', models.CharField(choices=[('H', 'H'), ('D', 'D')], max_length=1, null=True)),
                ('Edad', models.IntegerField(blank=True, null=True)),
                ('Procedencia', models.CharField(max_length=100, null=True)),
                ('Trabajo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('Beca', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('Convocatoria', models.CharField(blank=True, max_length=3, null=True)),
                ('Preferencia', models.IntegerField(blank=True, null=True)),
                ('Modalidad', models.CharField(blank=True, max_length=3, null=True)),
                ('Especialidad', models.CharField(blank=True, max_length=100, null=True)),
                ('Nota_Bach_Ciclo', models.FloatField(blank=True, null=True)),
                ('Nota_Prueba', models.FloatField(blank=True, null=True)),
                ('Nota_Especifica', models.FloatField(blank=True, null=True)),
                ('Nota_Admision', models.FloatField(blank=True, null=True)),
                ('Abandono', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('creditos_matriculados_primer_año', models.IntegerField(blank=True, null=True)),
                ('creditos_presentados_primer_año', models.IntegerField(blank=True, null=True)),
                ('creditos_aprobados_primer_año', models.IntegerField(blank=True, null=True)),
                ('creditos_matriculados_segundo_año', models.IntegerField(blank=True, null=True)),
                ('creditos_presentados_segundo_año', models.IntegerField(blank=True, null=True)),
                ('creditos_aprobados_segundo_año', models.IntegerField(blank=True, null=True)),
                ('media_primer_año', models.FloatField(blank=True, null=True)),
                ('media_segundo_año', models.FloatField(blank=True, null=True)),
                ('asignaturas', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None)),
                ('notas', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None)),
                ('Grado', models.CharField(max_length=150)),
                ('Ingreso', models.CharField(max_length=15)),
                ('Aciertos', models.IntegerField(blank=True, null=True)),
                ('Fallos', models.IntegerField(blank=True, null=True)),
                ('Total_prueba', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
