# Generated by Django 3.0.1 on 2020-11-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datos_alumnos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grado',
            old_name='creditos_aprobados_primer_año',
            new_name='asignaturas_aprobadas_primer_año',
        ),
        migrations.RenameField(
            model_name='grado',
            old_name='creditos_aprobados_segundo_año',
            new_name='asignaturas_aprobadas_segundo_año',
        ),
        migrations.RenameField(
            model_name='grado',
            old_name='creditos_matriculados_primer_año',
            new_name='asignaturas_matriculadas_primer_año',
        ),
        migrations.RenameField(
            model_name='grado',
            old_name='creditos_matriculados_segundo_año',
            new_name='asignaturas_matriculadas_segundo_año',
        ),
        migrations.RenameField(
            model_name='grado',
            old_name='creditos_presentados_primer_año',
            new_name='asignaturas_presentadas_primer_año',
        ),
        migrations.RenameField(
            model_name='grado',
            old_name='creditos_presentados_segundo_año',
            new_name='asignaturas_presentadas_segundo_año',
        ),
        migrations.RenameField(
            model_name='grado_rp30',
            old_name='creditos_aprobados_primer_año',
            new_name='asignaturas_aprobadas_primer_año',
        ),
        migrations.RenameField(
            model_name='grado_rp30',
            old_name='creditos_aprobados_segundo_año',
            new_name='asignaturas_aprobadas_segundo_año',
        ),
        migrations.RenameField(
            model_name='grado_rp30',
            old_name='creditos_matriculados_primer_año',
            new_name='asignaturas_matriculadas_primer_año',
        ),
        migrations.RenameField(
            model_name='grado_rp30',
            old_name='creditos_matriculados_segundo_año',
            new_name='asignaturas_matriculadas_segundo_año',
        ),
        migrations.RenameField(
            model_name='grado_rp30',
            old_name='creditos_presentados_primer_año',
            new_name='asignaturas_presentadas_primer_año',
        ),
        migrations.RenameField(
            model_name='grado_rp30',
            old_name='creditos_presentados_segundo_año',
            new_name='asignaturas_presentadas_segundo_año',
        ),
    ]
